'''
Base code of Pykc that doesn't require any imports
'''


def makeGrid(width, depth, height):
    return [[[None for k in xrange(height)] for j in xrange(depth)] for i in xrange(width)]


class BlockType:
    '''Sort of like an enum, but we literally want the string values and we don't
need any of the features we get from extending a Python Enum. This allows us to do 
things like this:

blocks[x][z][y] = bt.dirt
'''
    air = "AIR"
    stone = "STONE"
    granite = "GRANITE"
    polished_granite = "POLISHED_GRANITE"
    diorite = "DIORITE"
    polished_diorite = "POLISHED_DIORITE"
    andesite = "ANDESITE"
    polished_andesite = "POLISHED_ANDESITE"
    grass = "GRASS"
    dirt = "DIRT"
    coarse_dirt = "COARSE_DIRT"
    podzol = "PODZOL"
    cobblestone = "COBBLESTONE"
    oak_wood_plank = "OAK_WOOD_PLANK"
    spruce_wood_plank = "SPRUCE_WOOD_PLANK"
    birch_wood_plank = "BIRCH_WOOD_PLANK"
    jungle_wood_plank = "JUNGLE_WOOD_PLANK"
    acacia_wood_plank = "ACACIA_WOOD_PLANK"
    dark_oak_wood_plank = "DARK_OAK_WOOD_PLANK"
    bedrock = "BEDROCK"
    sand = "SAND"
    red_sand = "RED_SAND"
    gravel = "GRAVEL"
    oak_wood = "OAK_WOOD"
    spruce_wood = "SPRUCE_WOOD"
    birch_wood = "BIRCH_WOOD"
    jungle_wood = "JUNGLE_WOOD"
    sponge = "SPONGE"
    wet_sponge = "WET_SPONGE"
    sandstone = "SANDSTONE"
    chiseled_sandstone = "CHISELED_SANDSTONE"
    smooth_sandstone = "SMOOTH_SANDSTONE"
    white_wool = "WHITE_WOOL"
    orange_wool = "ORANGE_WOOL"
    magenta_wool = "MAGENTA_WOOL"
    light_blue_wool = "LIGHT_BLUE_WOOL"
    yellow_wool = "YELLOW_WOOL"
    lime_wool = "LIME_WOOL"
    pink_wool = "PINK_WOOL"
    gray_wool = "GRAY_WOOL"
    light_gray_wool = "LIGHT_GRAY_WOOL"
    cyan_wool = "CYAN_WOOL"
    purple_wool = "PURPLE_WOOL"
    blue_wool = "BLUE_WOOL"
    brown_wool = "BROWN_WOOL"
    green_wool = "GREEN_WOOL"
    red_wool = "RED_WOOL"
    black_wool = "BLACK_WOOL"
    gold_block = "GOLD_BLOCK"
    iron_block = "IRON_BLOCK"
    emerald_block = "EMERALD_BLOCK"
    diamond_block = "DIAMOND_BLOCK"
    lapis_lazuli_block = "LAPIS_LAZULI_BLOCK"
    bricks = "BRICKS"
    tnt = "TNT"
    bookshelf = "BOOKSHELF"
    moss_stone = "MOSS_STONE"
    obsidian = "OBSIDIAN"
    diamond_ore = "DIAMOND_ORE"
    emerald_ore = "EMERALD_ORE"
    gold_ore = "GOLD_ORE"
    iron_ore = "IRON_ORE"
    coal_ore = "COAL_ORE"
    lapis_lazuli_ore = "LAPIS_LAZULI_ORE"
    blue = "BLUE"
    green = "GREEN"
    white = "WHITE"
    red = "RED"
    pink = "PINK"
    black = "BLACK"
    yellow = "YELLOW"
    num0 = "NUM0"
    num1 = "NUM1"
    num2 = "NUM2"
    num3 = "NUM3"
    num4 = "NUM4"
    num5 = "NUM5"
    num6 = "NUM6"
    num7 = "NUM7"
    num8 = "NUM8"
    num9 = "NUM9"
    quartz_block = "QUARTZ_BLOCK"
    monster_spawner = "MONSTER_SPAWNER"
    crafting_table = "CRAFTING_TABLE"
    farmland = "FARMLAND"
    snow = "SNOW"
    ice = "ICE"
    snow_block = "SNOW_BLOCK"
    cactus = "CACTUS"
    clay = "CLAY"
    glass = "GLASS"
    still_lava = "STILL_LAVA"
    still_water = "STILL_WATER"
    flowing_lava = "FLOWING_LAVA"
    flowing_water = "FLOWING_WATER"


bt = BlockType
